-- 002 Tables: the normalised core model (3NF).
--
--   categories 1-* products *-1 suppliers
--   customers  1-* sales 1-* sale_items *-1 products
--                  sales 1-* payments
--   suppliers  1-* purchase_orders 1-* purchase_order_items *-1 products
--   products   1-* stock_movements      (the stock ledger)
--
-- Rules the data must always obey are declared here as constraints, so they
-- hold no matter what writes to the database - the API, the assistant, the SQL
-- console or a restore. Constraint names are explicit because the API turns
-- them into sentences a shopkeeper can act on (lib/dbErrors.js).

CREATE TABLE IF NOT EXISTS settings (
  key        text PRIMARY KEY,
  value      text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT settings_key_format CHECK (key ~ '^[a-z][a-z0-9_]{0,79}$')
);
COMMENT ON TABLE settings IS 'Business details and preferences as key/value pairs, so a new setting needs no migration.';

CREATE TABLE IF NOT EXISTS users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL,
  password_hash text NOT NULL,
  role          text NOT NULL DEFAULT 'staff',
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_role_check CHECK (role IN ('owner', 'manager', 'staff'))
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (lower(username));
COMMENT ON TABLE users IS 'Reserved for sign-in, which is not switched on yet.';

CREATE TABLE IF NOT EXISTS categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT categories_name_length CHECK (length(btrim(name)) BETWEEN 1 AND 100)
);
CREATE UNIQUE INDEX IF NOT EXISTS categories_name_key ON categories (lower(btrim(name)));
COMMENT ON TABLE categories IS 'Product groupings. Stored once and referenced, so renaming a category renames it everywhere.';

CREATE TABLE IF NOT EXISTS suppliers (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  contact_name text,
  phone        text,
  email        text,
  address      text,
  notes        text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  row_version  integer NOT NULL DEFAULT 1,
  CONSTRAINT suppliers_name_length CHECK (length(btrim(name)) BETWEEN 1 AND 150),
  CONSTRAINT suppliers_phone_length CHECK (phone IS NULL OR length(phone) <= 40),
  CONSTRAINT suppliers_email_format CHECK (email IS NULL OR email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);
COMMENT ON TABLE suppliers IS 'Businesses you buy stock from.';
COMMENT ON COLUMN suppliers.row_version IS 'Optimistic locking: bumped on every update so two people editing at once cannot overwrite each other.';

CREATE TABLE IF NOT EXISTS customers (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  phone       text,
  email       text,
  address     text,
  notes       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  row_version integer NOT NULL DEFAULT 1,
  CONSTRAINT customers_name_length CHECK (length(btrim(name)) BETWEEN 1 AND 150),
  CONSTRAINT customers_phone_length CHECK (phone IS NULL OR length(phone) <= 40),
  CONSTRAINT customers_email_format CHECK (email IS NULL OR email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);
COMMENT ON TABLE customers IS 'People and businesses you sell to.';

CREATE TABLE IF NOT EXISTS products (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku            text,
  name           text NOT NULL,
  description    text,
  category_id    bigint REFERENCES categories (id) ON DELETE SET NULL,
  unit           text NOT NULL DEFAULT 'unit',
  cost_price     numeric(14, 2) NOT NULL DEFAULT 0,
  sale_price     numeric(14, 2) NOT NULL DEFAULT 0,
  stock_quantity numeric(14, 3) NOT NULL DEFAULT 0,
  reorder_level  numeric(14, 3) NOT NULL DEFAULT 0,
  supplier_id    bigint REFERENCES suppliers (id) ON DELETE SET NULL,
  is_active      boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  row_version    integer NOT NULL DEFAULT 1,
  CONSTRAINT products_name_length CHECK (length(btrim(name)) BETWEEN 1 AND 200),
  CONSTRAINT products_sku_length CHECK (sku IS NULL OR length(sku) BETWEEN 1 AND 80),
  CONSTRAINT products_cost_price_check CHECK (cost_price >= 0),
  CONSTRAINT products_sale_price_check CHECK (sale_price >= 0),
  CONSTRAINT products_stock_quantity_check CHECK (stock_quantity >= 0),
  CONSTRAINT products_reorder_level_check CHECK (reorder_level >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS products_sku_key ON products (lower(sku)) WHERE sku IS NOT NULL;
COMMENT ON TABLE products IS 'The catalogue. stock_quantity is a running balance kept in step with stock_movements.';
COMMENT ON COLUMN products.stock_quantity IS 'Never negative - enforced by a CHECK, so overselling is impossible even when two sales land at once.';

CREATE TABLE IF NOT EXISTS sales (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference      text NOT NULL,
  customer_id    bigint REFERENCES customers (id) ON DELETE SET NULL,
  subtotal       numeric(14, 2) NOT NULL DEFAULT 0,
  discount       numeric(14, 2) NOT NULL DEFAULT 0,
  tax_rate       numeric(5, 2) NOT NULL DEFAULT 0,
  tax            numeric(14, 2) NOT NULL DEFAULT 0,
  total          numeric(14, 2) NOT NULL DEFAULT 0,
  amount_paid    numeric(14, 2) NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'unpaid',
  payment_method text,
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sales_reference_key UNIQUE (reference),
  CONSTRAINT sales_amounts_non_negative CHECK (subtotal >= 0 AND discount >= 0 AND tax >= 0 AND total >= 0),
  CONSTRAINT sales_tax_rate_range CHECK (tax_rate BETWEEN 0 AND 100),
  CONSTRAINT sales_discount_le_subtotal CHECK (discount <= subtotal),
  CONSTRAINT sales_total_consistent CHECK (total = subtotal - discount + tax),
  CONSTRAINT sales_paid_range CHECK (amount_paid >= 0 AND amount_paid <= total),
  CONSTRAINT sales_payment_status_check CHECK (payment_status IN ('unpaid', 'partial', 'paid', 'refunded'))
);
COMMENT ON TABLE sales IS 'One row per receipt. amount_paid and payment_status are derived from payments by a trigger.';

-- description and unit_cost are copied at the moment of sale on purpose: rename
-- a product or change its cost later and old receipts and old profit stay true.
CREATE TABLE IF NOT EXISTS sale_items (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id     bigint NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
  product_id  bigint REFERENCES products (id) ON DELETE SET NULL,
  description text NOT NULL,
  quantity    numeric(14, 3) NOT NULL,
  unit_price  numeric(14, 2) NOT NULL DEFAULT 0,
  unit_cost   numeric(14, 2) NOT NULL DEFAULT 0,
  line_total  numeric(14, 2) GENERATED ALWAYS AS (round(quantity * unit_price, 2)) STORED,
  CONSTRAINT sale_items_description_length CHECK (length(btrim(description)) BETWEEN 1 AND 250),
  CONSTRAINT sale_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT sale_items_prices_non_negative CHECK (unit_price >= 0 AND unit_cost >= 0)
);
COMMENT ON COLUMN sale_items.unit_cost IS 'Cost price snapshot at the time of sale - makes profit reporting exact.';
COMMENT ON COLUMN sale_items.line_total IS 'Generated column: always quantity x unit price, rounded to cents.';

CREATE TABLE IF NOT EXISTS payments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id    bigint NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
  amount     numeric(14, 2) NOT NULL,
  method     text NOT NULL DEFAULT 'cash',
  kind       text GENERATED ALWAYS AS (CASE WHEN amount < 0 THEN 'refund' ELSE 'payment' END) STORED,
  note       text,
  paid_at    timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payments_amount_non_zero CHECK (amount <> 0),
  CONSTRAINT payments_method_check CHECK (method IN ('cash', 'card', 'upi', 'bank', 'other'))
);
COMMENT ON TABLE payments IS 'Money received against a sale. A negative amount is a refund. Several rows make a part-payment history.';

CREATE TABLE IF NOT EXISTS purchase_orders (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference     text NOT NULL,
  supplier_id   bigint REFERENCES suppliers (id) ON DELETE SET NULL,
  status        text NOT NULL DEFAULT 'draft',
  expected_date date,
  received_date date,
  total         numeric(14, 2) NOT NULL DEFAULT 0,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT purchase_orders_reference_key UNIQUE (reference),
  CONSTRAINT purchase_orders_status_check CHECK (status IN ('draft', 'ordered', 'partial', 'received', 'cancelled')),
  CONSTRAINT purchase_orders_total_check CHECK (total >= 0)
);
COMMENT ON TABLE purchase_orders IS 'Stock ordered from a supplier. Status follows what has actually been received.';

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id bigint NOT NULL REFERENCES purchase_orders (id) ON DELETE CASCADE,
  product_id        bigint REFERENCES products (id) ON DELETE SET NULL,
  description       text NOT NULL,
  quantity          numeric(14, 3) NOT NULL,
  quantity_received numeric(14, 3) NOT NULL DEFAULT 0,
  unit_cost         numeric(14, 2) NOT NULL DEFAULT 0,
  line_total        numeric(14, 2) GENERATED ALWAYS AS (round(quantity * unit_cost, 2)) STORED,
  CONSTRAINT purchase_order_items_description_length CHECK (length(btrim(description)) BETWEEN 1 AND 250),
  CONSTRAINT purchase_order_items_quantity_positive CHECK (quantity > 0),
  CONSTRAINT purchase_order_items_received_range CHECK (quantity_received >= 0 AND quantity_received <= quantity),
  CONSTRAINT purchase_order_items_cost_check CHECK (unit_cost >= 0)
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     bigint NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  change         numeric(14, 3) NOT NULL,
  balance_after  numeric(14, 3) NOT NULL,
  kind           text NOT NULL,
  reference_type text,
  reference_id   bigint,
  note           text,
  actor          text NOT NULL DEFAULT 'system',
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_movements_change_non_zero CHECK (change <> 0),
  CONSTRAINT stock_movements_balance_check CHECK (balance_after >= 0),
  CONSTRAINT stock_movements_kind_check CHECK (kind IN ('opening', 'sale', 'sale_void', 'purchase_receipt', 'adjustment', 'correction', 'import'))
);
COMMENT ON TABLE stock_movements IS 'The stock ledger: every change to every product''s stock, why it happened and the balance after. Written by triggers, never by hand.';

CREATE TABLE IF NOT EXISTS message_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel      text NOT NULL DEFAULT 'email',
  recipient    text,
  subject      text,
  body         text,
  trigger_type text,
  status       text NOT NULL DEFAULT 'queued',
  related_type text,
  related_id   bigint,
  error        text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  sent_at      timestamptz,
  CONSTRAINT message_log_channel_check CHECK (channel IN ('email', 'sms', 'whatsapp')),
  CONSTRAINT message_log_status_check CHECK (status IN ('queued', 'sent', 'failed'))
);
COMMENT ON TABLE message_log IS 'Alerts and confirmations DocDesk decided to send. Delivery is simulated until a provider is connected.';

CREATE TABLE IF NOT EXISTS files (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stored_name   text NOT NULL,
  original_name text NOT NULL,
  mime_type     text NOT NULL,
  size_bytes    bigint NOT NULL DEFAULT 0,
  description   text,
  related_type  text,
  related_id    bigint,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT files_stored_name_key UNIQUE (stored_name),
  CONSTRAINT files_size_check CHECK (size_bytes >= 0),
  CONSTRAINT files_related_type_check CHECK (related_type IS NULL OR related_type IN ('product', 'sale', 'customer', 'supplier', 'purchase_order')),
  CONSTRAINT files_related_pair CHECK ((related_type IS NULL) = (related_id IS NULL))
);
COMMENT ON TABLE files IS 'Metadata for uploaded documents. The bytes live on disk under a generated name.';

CREATE TABLE IF NOT EXISTS audit_log (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  table_name     text NOT NULL,
  record_id      bigint,
  record_key     text,
  action         text NOT NULL,
  actor          text NOT NULL DEFAULT 'system',
  changed_fields text[],
  old_data       jsonb,
  new_data       jsonb,
  txid           bigint NOT NULL DEFAULT txid_current(),
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_action_check CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);
COMMENT ON TABLE audit_log IS 'Every insert, update and delete on business tables, with before and after values. Written by triggers.';
