-- 007 Saved queries: the SQL console's own library.
--
-- Kept in the database rather than the browser, so a query someone worked out
-- once is there on every machine, survives a reinstall, and goes into backups
-- with everything else.

CREATE TABLE IF NOT EXISTS saved_queries (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text,
  sql         text NOT NULL,
  pinned      boolean NOT NULL DEFAULT false,
  run_count   integer NOT NULL DEFAULT 0,
  last_run_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT saved_queries_name_length CHECK (char_length(btrim(name)) BETWEEN 1 AND 120),
  CONSTRAINT saved_queries_sql_length CHECK (char_length(btrim(sql)) BETWEEN 1 AND 20000),
  CONSTRAINT saved_queries_run_count_positive CHECK (run_count >= 0)
);
COMMENT ON TABLE saved_queries IS 'Queries saved from the SQL console, with how often each has been run.';

-- One query per name, however it was capitalised or spaced.
CREATE UNIQUE INDEX IF NOT EXISTS saved_queries_name_key ON saved_queries (lower(btrim(name)));
CREATE INDEX IF NOT EXISTS saved_queries_pinned_idx ON saved_queries (pinned DESC, last_run_at DESC NULLS LAST);

CREATE OR REPLACE TRIGGER saved_queries_touch BEFORE UPDATE ON saved_queries
  FOR EACH ROW EXECUTE FUNCTION touch_row();
